project:
  type: website

website:
  title: "Intro To Programming"
  favicon: /images/unito-shield.png
  twitter-card: true
  google-analytics: "G-TQGG8QBSRH"
  body-footer: © Florian Oswald, 2025
  sidebar:
    style: "docked"
    contents:
      - section: "Lessons:"
        contents:
          - href: 01-shell-intro.qmd
            text: 1. Shell Intro
          - href: 02-filedir.qmd
            text: 2. Files and Directories
          - href: 03-filework.qmd
            text: 3. Working with Files
          - href: https://floswald.github.io/2025-09-30-PythonIntro/
            text: 4. Python Workshop
          - href: https://raw.githack.com/ScPoEcon/ScPoEconometrics-Slides/master/chapter_intro_programming/chapter_intro.html
            text: 13. `R` intro
          - href: https://raw.githack.com/ScPoEcon/ScPoEconometrics-Slides/master/chapter_tidy_programming/chapter_tidy.html
            text: 14. `R Tidyverse`
          - href: https://raw.githack.com/floswald/lectures/master/05-datatable/05-datatable.html
            text: 15. `R data.table`
          - href: 09-R-packages.qmd
            text: 16. Building `R` packages
          - href: 10-spatial-R.qmd
            text: 17. Spatial Data with `R`

  navbar:
    left:
      - href: index.qmd
        text: Home
    logo: /images/unito-red.png
    foreground: "#ba0202"
    background: "#faf7f7"
format:
  html:
    theme: journal
    linkcolor: "#ba0202"
    css: styles.css
    toc: true
    highlight-style: github







