---
title: Intro To Programming
author: "[Florian Oswald](https://floswald.github.io)"
subtitle: "UniTo Master in Economics"
number-sections: true
---

# Welcome to *Introduction to Programming*

* This website is the home of the course _Introduction to Programming_.
* This course assumes **no prior programming** experience.
* Below you will find setup instructions and a syllabus.
* You can obtain all material for this course from the associated github repository at [link](https://github.com/floswald/IntroProgramming/)

## Objectives of this Course

* After this course, we want you to be able to participate or conduct your own research project in an efficient way. *Research* nowadays means data sciencey stuff in most cases, certainly in Economics. 
* We want you to have a basic understanding of how an operating system (in particular, *your* OS) works.
* We want to be able to achieve a basic level of automation in repetitive tasks.
* We want you to know what Version Control is and how to use it in a research project.
* We will introduce some (hopefully) useful `R` programming.

# Program

This course has several submodules. 

1. Installing Software and Preparing environment (you do that at home, see below [@sec-setup)
2. OS Basics: What *is* an OS, how to work with it.
3. Python
4. R
5. julia (maybe)

| Module | Session Number |  Topic      |  Author |
|:------------:|:------------:|:-----------|:-------------:|
| OS Basics    | 1        | [The Unix Shell](01-shell-intro.qmd) |  [The Software Carpentry Project](https://software-carpentry.org/) + Florian Oswald |
| OS Basics    | 2            | [Shell: Files and Directories](02-filedir.qmd) |  [The Software Carpentry Project](https://software-carpentry.org/) + Florian Oswald |
| OS Basics    | 3            | [Shell: Working with Files and Directories](03-filework.qmd) |  [The Software Carpentry Project](https://software-carpentry.org/) + Florian Oswald |
|              |              | [Homework 1](https://github.com/floswald/scpoproghw1): complete and run a bash script on gh-actions |  Florian Oswald |
| Python       | 4-12         | [Python Intro](https://floswald.github.io/2025-09-30-PythonIntro/) |  [The Software Carpentry Project](https://software-carpentry.org/) + Florian Oswald |
| R            | 13            | [`R` Intro](https://raw.githack.com/ScPoEcon/ScPoEconometrics-Slides/master/chapter_intro_programming/chapter_intro.html) |  Florian Oswald|
| R            | 14           | [`R {tidyverse}`](https://raw.githack.com/ScPoEcon/ScPoEconometrics-Slides/master/chapter_tidy_programming/chapter_tidy.html) | [Grant McDermott](https://grantmcdermott.| R            com/)  + Florian Oswald|
| R            | 15            | [`R` and `python` generics](06-concepts.qmd) | Florian Oswald|
| R            | 16            | [`R {data.table}`](https://raw.githack.com/floswald/lectures/master/05-datatable/05-datatable.html) | [Grant McDermott](https://grantmcdermott.com/)  + Florian Oswald|
| R            | 17            | [Building `R` packages](09-R-packages.qmd) |  Florian Oswald|
| R            | 18            | [Spatial Data with `R`](10-spatial-R.qmd) |  Florian Oswald|


Optional Material

| Module | Session Number |  Topic      |  Author |
|:------------:|:------------:|:-----------|:-------------:|
| `*`          |  | [Shell: Pipes and Filters](04-pipes.qmd) |  [The Software Carpentry Project](https://software-carpentry.org/) + Florian Oswald |
| `*`          |  | [`Git` Version Control](05-git.qmd) |  [The Software Carpentry Project](https://software-carpentry.org/) + Florian Oswald |
| julia            | 19            | [`julia` intro 1](https://floswald.github.io/julia-bootcamp/01-variables.html) |  Florian Oswald|
| julia            | 20            | [`julia` intro 2](https://floswald.github.io/julia-bootcamp/02-functions.html) |  Florian Oswald|
| R            | 21            | [Quick Intro to NLP with R](11-NLP-R.qmd) |  Florian Oswald|



# Setup Instructions {#sec-setup}

* You must bring your own laptop to each class.
* Please make sure you have an up to date operating system, i.e. run a software update before we start.


::: {.callout-important}

# Very Detailed Installation Instructions

* I put together a suite of *extremely* detailed installation instructions. You should follow those [here](https://floswald.github.io/2025-09-30-PythonIntro/#setup) before coming to the first session in class!
* Each Operating System has different instructions to follow.

:::


# Code of Conduct

If you decide to participate in this course, I expect you to abide by the following minimal code of conduct.

1. Be polite to the other class participants. 
2. While in class, do not spend time on messaging apps, chat rooms, computer games, or similar content.

You can expect your instructor to abide by the same code of conduct, so this is a matter of mutual respect. If you are found in breach of the above you will be given a single warning, and I will ask you to no longer join the course after a second time. Your grade will be "fail".



# License

All lectures of this course are derived from the work of the [Software Carpentry](https://software-carpentry.org/license/). Their material is licensed under [creative commons license 4.0](https://creativecommons.org/licenses/by/4.0/), whereby I am allowd to share and remix the content, if appropriate attribution is given. 

Those terms apply to anyone wanting use material on this website as well. Thank you.